# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/
            guard:
                authenticators:
                    - api_authenticator
            stateless: true
            logout:
                target: homepage

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /discourse/sso, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /contact, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/events$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/events/[0-9]+$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /about-us, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, roles: [ROLE_USER], requires_channel: https }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_USER_PRO: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SUBSCRIBER_STANDARD, ROLE_USER_PRO]