# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    guzzle.client.api:
        class: AppBundle\Service\ApiClient
        arguments:
            -
             'requestStack': "@request_stack"
             'baseUrl' : "%api_base_url%"
             'verify': "%api_ssl_checking%"
             'authenticationCookieName': "%auth_cookie.name%"
    api_authenticator :
        class: AppBundle\Security\ApiAuthenticator
        arguments: ["@router", "@guzzle.client.api", "%auth_cookie.name%"]

    logout_listener:
        class: AppBundle\Listener\LogoutListener
        arguments: [ "%auth_cookie.domain%", "%auth_cookie.name%", "@guzzle.client.api", "@logger"]
        tags:
           - { name: kernel.event_listener, event: kernel.response }

    ABTest.service:
        class: AppBundle\Service\ABTest
        arguments: ["@request_stack", "%abtest_cookie.domain%", "%abtest_cookie.name%", "%abtest_configuration%"]
        tags:
          - { name: kernel.event_listener, event: kernel.response }


